import Head from 'next/head';
import Hero from '../components/Hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next App with tailwind</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero
        heading='Hi, there I am  Usman, a fullstack developer'
        massege='Passionate, Motivated fullstack devloper who design thoughtful digital experiences.'
      />
    </div>
  );
}
